applicationName: POC-Groovy-Reload-With-ClassLoader-Isolation
scriptsDirectory: src/dist/scripts

http:
  mappers:
    jsonPrettyPrint: true

management:
  port: 8081
  address: 127.0.0.1
  security:
    enabled: false